#!/bin/sh
rm ./data02/drop_rate7_o
rm ./data02/delay_rate7_o
rm ./data02/throughput_rate7_o

#for a in $(seq 30)   #flow的个数
for a in 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150;
do
	for b in $(seq 100)     #测试的次数
	do
		ns wireless-aodv-tdma.tcl 5 $a 7 > ./data02/data02.tcl

		echo -n "$a	" >> ./data02/drop_rate7_o
		gawk -f drop.awk aodv-tdma.tr >> ./data02/drop_rate7_o

		echo -n "$a	" >> ./data02/delay_rate7_o
		gawk -f delay.awk aodv-tdma.tr >> ./data02/delay_rate7_o

		echo -n "$a	" >> ./data02/throughput_rate7_o
		gawk -f throughput.awk aodv-tdma.tr >> ./data02/throughput_rate7_o
	done
done
rm ./data02/average_data/drop_ave7_o
rm ./data02/average_data/delay_ave7_o
rm ./data02/average_data/throughput_ave7_o
gawk -f ./data02/average.awk ./data02/drop_rate7_o > ./data02/average_data/drop_ave7_o
gawk -f ./data02/average.awk ./data02/delay_rate7_o > ./data02/average_data/delay_ave7_o
gawk -f ./data02/average.awk ./data02/throughput_rate7_o > ./data02/average_data/throughput_ave7_o
exit 0
