#!/bin/sh
rm ./data02/drop_rate9o_flow10
rm ./data02/delay_rate9o_flow10
rm ./data02/throughput_rate9o_flow10

#for a in $(seq 30)   #flow的个数
for a in 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150;
do
	for b in $(seq 200)     #测试的次数
	do
		ns wireless-aodv-tdma.tcl 10 $a 9 > ./data02/data02.tcl

		echo -n "$a	" >> ./data02/drop_rate9o_flow10
		gawk -f drop.awk aodv-tdma.tr >> ./data02/drop_rate9o_flow10

		echo -n "$a	" >> ./data02/delay_rate9o_flow10
		gawk -f delay.awk aodv-tdma.tr >> ./data02/delay_rate9o_flow10

		echo -n "$a	" >> ./data02/throughput_rate9o_flow10
		gawk -f throughput.awk aodv-tdma.tr >> ./data02/throughput_rate9o_flow10
	done
done
rm ./data02/average_data/drop_ave9o_flow10
rm ./data02/average_data/delay_ave9o_flow10
rm ./data02/average_data/throughput_ave9o_flow10
gawk -f ./data02/average.awk ./data02/drop_rate9o_flow10 > ./data02/average_data/drop_ave9o_flow10
gawk -f ./data02/average.awk ./data02/delay_rate9o_flow10 > ./data02/average_data/delay_ave9o_flow10
gawk -f ./data02/average.awk ./data02/throughput_rate9o_flow10 > ./data02/average_data/throughput_ave9o_flow10
exit 0
